default_language_version:
    python: python3.9
default_stages: [pre-commit, pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      types: [python]
      exclude: (venv/)

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config, ".flake8", --extend-exclude, "*/venv/*"]
